
#' Harvest component of operating model
#'
#' A function used by openMSE to specify the fishing effort during the projections.
#' salmonMSE updates the arguments of this function from the salmon operating model.
#'
#' @param x Simulation number
#' @param DataList A nested list of \linkS4class{Data} objects by stock then fleet, generated by [multiMSE()]
#' @param reps The number of stochastic replicates to be returned by the function
#' @param u_terminal Harvest rate of retained catch in the terminal fishery
#' @param u_preterminal Harvest rate of retained catch in the pre-terminal fishery
#' @param m Mark rate of hatchery origin fish, as a proxy for fishery retention. Only used to calculate the fishing effort.
#' Retention in the operating model is specified in the \linkS4class{MOM} object
#' @param release_mort Length two numeric for the release mortality of discarded fish in the pre-terminal and terminal fishery. Only used to calculate the fishing effort.
#' Release mortality in the operating model is specified in the \linkS4class{MOM} object
#' @param p_terminal Population index for the recruitment that experiences the terminal fishing mortality
#' @param p_preterminal Population index for immature fish that experience the pre-terminal fishing mortality
#' @param ... Not used
#'
#' @return A nested list of \linkS4class{Rec} objects, same dimension as `DataList`
#'
#' @keywords internal
Harvest_MMP <- function(x = 1, DataList, reps = 1, u_terminal, u_preterminal, m, release_mort,
                        p_terminal = c(2, 5), p_preterminal = c(1, 4), ...) {
  np <- length(DataList)
  nf <- length(DataList[[1]])

  multiRec <- lapply(1:np, function(p) {

    if (p %in% p_terminal) {
      if (m > 0) {
        Effort <- get_F(u = u_terminal, M = 0, ret = m, release_mort = release_mort[2])
      } else {
        Effort <- -log(1 - u_terminal)
      }
    } else if (p %in% p_preterminal) {
      if (u_preterminal > 0) {
        y <- max(DataList[[1]][[1]]@Year) - DataList[[1]][[1]]@LHYear + 1
        nyears <- length(DataList[[1]][[1]]@Misc$FleetPars$Find[x, ])
        M <- DataList[[p]][[1]]@Misc$StockPars$M_ageArray[x, , nyears + y]
        F_preterminal <- get_F(u = u_preterminal, M = max(M), ret = ifelse(m > 0, m, 1), release_mort = SOM@release_mort[1])
      } else {
        F_preterminal <- 0
      }
      Effort <- F_preterminal
    } else {
      Effort <- 0
    }

    lapply(1:nf, function(f) {
      Rec <- new("Rec")
      HistE <- DataList[[p]][[f]]@OM$FinF[x] # Last historical fishing effort
      Rec@Effort <- rep(Effort/HistE, reps)
      return(Rec)
    })
  })
  return(multiRec)
}

#' Harvest component of salmon operating model
#'
#' A function that creates a multi-stock management procedure
#'
#' @param u_terminal Numeric between 0-1. Harvest rate of the terminal fishery.
#' @param u_preterminal Numeric between 0-1. Harvest rate of the preterminal fishery.
#' @param m Numeric between 0-1. Mark rate, i.e., retention rate.
#' @param release_mort Vector length 2 (each numeric between 0-1). Release mortality, proportion of released fish that die.
#'
#' @export
make_Harvest_MMP <- function(u_terminal = 0.1, u_preterminal = 0, m = 0, release_mort = 0) {
  f <- Harvest_MMP
  formals(f)$u_terminal <- u_terminal
  formals(f)$u_preterminal <- u_preterminal
  formals(f)$m <- m
  formals(f)$release_mort <- release_mort
  class(f) <- "MMP"
  return(f)
}

#' Calculate F from harvest rate
#'
#' Solves for instantaneous fishing mortality rate from harvest rate
#'
#' @param u Harvest rate, between 0-1
#' @param M Instantaneous natural mortality rate
#' @param ret Retention rate, between 0-1
#' @param release_mort Release mortality as a proportion, between 0-1
#' @param Fmax Maximum allowable value of F
#' @return Numeric
#'
#' @keywords internal
#'
#' @importFrom stats uniroot
get_F <- function(u = 0, M, ret = 0, release_mort = 0, Fmax = 20) {
  if (u > 0) {
    .F <- uniroot(F_solver, interval = c(1e-8, Fmax), M = M, ret = ret, release_mort = release_mort, u = u)
    .F$root
  } else {
    0
  }
}

F_solver <- function(.F, M, ret, release_mort, u = 0) {
  Z <- ret * .F + (1 - ret) * release_mort * .F + M
  ret * .F/Z * (1 - exp(-Z)) - u
}

